const productsDatabase = [
    // --- دسته ۱۱: باکس الگانت ---
    {
        id: 11001,
        categoryId: 11,
        name: "باکس الگانت ویژه",
        price: 380000,
        priceText: "۳۸۰,۰۰۰ تومان", // برای نمایش راحت‌تر
        description: "فینگرفودهای لقمه‌ای با طعم‌های مدیترانه‌ای مناسب برای ۴ نفر",
        image: "image1/47.jpg",
        rating: 4.0,
        badge: "جدید",
        details: { // جزئیات اضافی برای صفحه محصول
            calories: "400 kcal",
            ingredients: "پنیر پستو، گوجه گیلاسی، نان تارت، ریحان"
        }
    },
    {
        id: 11002,
        categoryId: 11,
        name: "باکس سوپرایز",
        price: 420000,
        priceText: "۴۲۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/109.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11003,
        categoryId: 11,
        name: "پک دفاع",
        price: 260000,
        priceText: "۲۶۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/23.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11004,
        categoryId: 11,
        name: "پک صبحانه",
        price: 170000,
        priceText: "۱۷۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/30.jpeg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11005,
        categoryId: 11,
        name: "پک ترحیم",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/81.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11006,
        categoryId: 11,
        name: "پک دفاع",
        price: 410000,
        priceText: "۴۱۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/89.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11007,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/77.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11008,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/59.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11009,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/56.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11010,
        categoryId: 11,
        name: "پک دفاع",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/42.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11011,
        categoryId: 11,
        name: "پک دفاع",
        price: 540000,
        priceText: "۵۴۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/26.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { calories: "500 kcal", ingredients: "مخلوط" }
    },
    // --- دسته ۱۲: فینگر فود و مزه ---
    {
        id: 12001,
        categoryId: 12,
        name: "پیراشکی گوشت و قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12002,
        categoryId: 12,
        name: "پیراشکی مرغ قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12003,
        categoryId: 12,
        name: "پیراشکی پیتزایی",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12005,
        categoryId: 12,
        name: "مینی برگر",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/124.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
{
        id: 12006,
        categoryId: 12,
        name: "مینی چیز برگر",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/140.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12007,
        categoryId: 12,
        name: "مینی چیکن برگر",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12008,
        categoryId: 12,
        name: "مینی ساندویچ ژامبون",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/75.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12009,
        categoryId: 12,
        name: "مینی ساندویچ الویه",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12010,
        categoryId: 12,
        name: "مینی ساندویچ مرغ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12011,
        categoryId: 12,
        name: "مینی ساندویچ فلافل",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12012,
        categoryId: 12,
        name: "مینی هات داگ",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12013,
        categoryId: 12,
        name: "رول لازنیا",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12014,
        categoryId: 12,
        name: "پیراشکی سوخاری",
        price: 68000,
        priceText: "۶۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/145.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12015,
        categoryId: 12,
        name: "فیله سوخاری",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12016,
        categoryId: 12,
        name: "رول ژامبون سوخاری",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/121.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12017,
        categoryId: 12,
        name: "توپک مرغ پنیری سوخاری",
        price: 45000,
        priceText: "۴۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12018,
        categoryId: 12,
        name: "توپک سیب زمینی پنیری سوخاری",
        price: 45000,
        priceText: "۴۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12019,
        categoryId: 12,
        name: "دونات مرغ سوخاری",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12020,
        categoryId: 12,
        name: "شات اسپرینگ رول",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12021,
        categoryId: 12,
        name: "شات سالاد ماکارونی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12022,
        categoryId: 12,
        name: "شات فیله سوخاری",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12023,
        categoryId: 12,
        name: "شات کشک بادمجان",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/66.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12024,
        categoryId: 12,
        name: "شات قفقازی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12025,
        categoryId: 12,
        name: "شات سالادالویه",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/142.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
   
    {
        id: 12026,
        categoryId: 12,
        name: "مینی پیتزا گوشت قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12027,
        categoryId: 12,
        name: "مینی پیتزا مرغ و قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12028,
        categoryId: 12,
        name: "مینی پیتزا پپرونی",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12029,
        categoryId: 12,
        name: "مینی پیتزای سوسیس و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12031,
        categoryId: 12,
        name: "بورک گوشت و قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12032,
        categoryId: 12,
        name: "بورک مرغ و قارچ",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12033,
        categoryId: 12,
        name: "بورک سوسیس و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12034,
        categoryId: 12,
        name: "تارت گوشت و قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/71.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12035,
        categoryId: 12,
        name: "تارت مرغ و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12036,
        categoryId: 12,
        name: "تارت کشک بادمجان",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/65.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12037,
        categoryId: 12,
        name: "کیک مرغ تکنفره",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/43.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12038,
        categoryId: 12,
        name: "کیک مرغ کیلویی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/25.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12039,
        categoryId: 12,
        name: "کوکو لوبیا",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/122.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12040,
        categoryId: 12,
        name: "کوکو سبزی",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
       {
        id: 12041,
        categoryId: 12,
        name: "قیف الویه",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/111.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12042,
        categoryId: 12,
        name: "سالاد الویه کیلویی",
        price: 800000,
        priceText: "۸۰۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12043,
        categoryId: 12,
        name: "قفقاز کیلویی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12044,
        categoryId: 12,
        name: "کشک بادمجان کیلویی",
        price: 800000,
        priceText: "۸۰۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12045,
        categoryId: 12,
        name: "سالاد ماکارونی کیلویی",
        price: 700000,
        priceText: "۷۰۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/31.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12046,
        categoryId: 12,
        name: "ته چین مرغ زعفرانی ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/44.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12047,
        categoryId: 12,
        name: "ته چین مرغ زعفرانی قالبی",
        price: 110000,
        priceText: "۱۱۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12048,
        categoryId: 12,
        name: "سالاد سزار",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/127.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12049,
        categoryId: 12,
        name: "سالاد کلم",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12050,
        categoryId: 12,
        name: "سالاد کلم",
        price: 59000,
        priceText: "۵۹,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
       {
        id: 12051,
        categoryId: 12,
        name: "سالاد مرغ",
        price: 59000,
        priceText: "۵۹,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12052,
        categoryId: 12,
        name: "سالاد اندونزی",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12053,
        categoryId: 12,
        name: "سالاد روسی",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12054,
        categoryId: 12,
        name: "سمبوسه",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12055,
        categoryId: 12,
        name: "اسپرینگ رول",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/45.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12056,
        categoryId: 12,
        name: "رولت الویه",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/107.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    {
        id: 12057,
        categoryId: 12,
        name: "خیار ماست",
        price: 25000,
        priceText: "۲۵,۰۰۰ تومان",
        description: "ترکیبی از زیتون، پنیرهای متنوع، آجیل و میوه‌های خشک",
        image: "image1/130.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { calories: "350 kcal", ingredients: "زیتون، پنیر گودا، گردو" }
    },
    
    // --- دسته ۱۳: دسر و نوشیدنی ---
    {
        id: 13001,
        categoryId: 13,
        name: "لوتوس",
        price: 65000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/19.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13002,
        categoryId: 13,
        name: "تیرامیسو",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13003,
        categoryId: 13,
        name: "روکر موز",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/2.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13004,
        categoryId: 13,
        name: "چیز کیک لوتوس",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
{
     id: 13005,
        categoryId: 13,
        name: "ژله بستنی",
        price: 40000,
        priceText: "۴۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/5.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13006,
        categoryId: 13,
        name: "کرم توت فرنگی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13007,
        categoryId: 13,
        name: "دسر شکلاتی ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/4.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13008,
        categoryId: 13,
        name: "کرم زعفرانی",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13009,
        categoryId: 13,
        name: "کرم وانیلی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/144.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
     {
     id: 13010,
        categoryId: 13,
        name: "چیز کیک رافائل",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/68.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
     {
     id: 13011,
        categoryId: 13,
        name: "خاگینه مغز دار",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
     {
     id: 13012,
        categoryId: 13,
        name: "حلوا فیروزه",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/113.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13013,
        categoryId: 13,
        name: "شربت زعفران",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/125.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
     {
     id: 13014,
        categoryId: 13,
        name: "کاپ کیک ساده",
        price: 41000,
        priceText: "۴۱,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/119.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    {
     id: 13015,
        categoryId: 13,
        name: "کاپ کیک ساده فیلنگ دار",
        price: 46000,
        priceText: "۴۶,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/118.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
  {
    id: 13016,
        categoryId: 13,
        name: "پاناکوتا",
        price: 60000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "مجموعه‌ای از مینی تارت‌های میوه‌ای",
        image: "image1/117.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { calories: "200 kcal", ingredients: "خامه، توت فرنگی، نان تارت" }
    },
    // --- دسته ۱۴: وی‌آی‌پی (VIP) ---
    {
        id: 14001,
        categoryId: 14,
        name: "سینی رویال وی‌آی‌پی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "لوکس‌ترین سینی فیروزه مخصوص مهمانی‌های خاص",
        image: "image1/vip1.png",
        rating: 5.0,
        badge: "ویژه",
        details: { calories: "800 kcal", ingredients: "خاویار، سالمون دودی، پنیر کمیاب" }
    },

    // --- دسته ۱۵: نیمه آماده ---
    {
        id: 15001,
        categoryId: 15,
        name: "الویه نیمه آماده",
        price: 120000,
        priceText: "۱۲۰,۰۰۰ تومان",
        description: "مواد اولیه الویه آماده ترکیب",
        image: "image1/semi1.png",
        rating: 4.2,
        badge: "",
        details: { calories: "300 kcal", ingredients: "سیب زمینی، مرغ، خیارشور" }
    },
     {
        id: 15002,
        categoryId: 15,
        name: "رول سوخاری نیمه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "مواد اولیه الویه آماده ترکیب",
        image: "image1/87.jpg",
        rating: 4.2,
        badge: "",
        details: { calories: "300 kcal", ingredients: "سیب زمینی، مرغ، خیارشور" }
    },
    {
        id: 15003,
        categoryId: 15,
        name: "سمبوسه نیه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "مواد اولیه الویه آماده ترکیب",
        image: "image1/86.jpg",
        rating: 4.2,
        badge: "",
        details: { calories: "300 kcal", ingredients: "سیب زمینی، مرغ، خیارشور" }
    },
    {
        id: 15003,
        categoryId: 15,
        name: "بورک مرغ و قارچ نیمه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "مواد اولیه الویه آماده ترکیب",
        image: "image1/83.jpg",
        rating: 4.2,
        badge: "",
        details: { calories: "300 kcal", ingredients: "سیب زمینی، مرغ، خیارشور" }
    },


    // --- دسته ۱۶: خدمات سازمانی ---
    {
        id: 16001,
        categoryId: 16,
        name: "پک صبحانه سازمانی",
        price: 85000,
        priceText: "۸۵,۰۰۰ تومان",
        description: "پک تک نفره صبحانه اداری",
        image: "image1/org1.png",
        rating: 4.6,
        badge: "اقتصادی",
        details: { calories: "450 kcal", ingredients: "نان، پنیر، گردو، چای" }
    }
];