const productsDatabase = [
    // --- دسته ۱۱: باکس الگانت ---
    {
        id: 11001,
        categoryId: 11,
        name: "باکس الگانت ویژه",
        price: 380000,
        priceText: "۳۸۰,۰۰۰ تومان", // برای نمایش راحت‌تر
        description: "فینگرفودهای لقمه‌ای با طعم‌های مدیترانه‌ای مناسب برای ۴ نفر",
        image: "image1/47.jpg",
        rating: 4.0,
        badge: "جدید",
        details: { // جزئیات اضافی برای صفحه محصول
            nutrition_info: "400 kcal",
            ingredients: "پنیر پستو، گوجه گیلاسی، نان تارت، ریحان"
        }
    },
    {
        id: 11002,
        categoryId: 11,
        name: "باکس سوپرایز",
        price: 420000,
        priceText: "۴۲۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/109.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11003,
        categoryId: 11,
        name: "پک دفاع",
        price: 260000,
        priceText: "۲۶۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/23.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11004,
        categoryId: 11,
        name: "پک صبحانه",
        price: 170000,
        priceText: "۱۷۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/30.jpeg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11005,
        categoryId: 11,
        name: "پک ترحیم",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/81.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11006,
        categoryId: 11,
        name: "پک دفاع",
        price: 410000,
        priceText: "۴۱۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/89.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11007,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/77.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11008,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/59.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11009,
        categoryId: 11,
        name: "پک تولد",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/56.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11010,
        categoryId: 11,
        name: "پک دفاع",
        price: 280000,
        priceText: "۲۸۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/42.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    {
        id: 11011,
        categoryId: 11,
        name: "پک دفاع",
        price: 540000,
        priceText: "۵۴۰,۰۰۰ تومان",
        description: "یک باکس هیجان‌انگیز برای هدیه",
        image: "image1/26.jpg",
        rating: 5.0,
        badge: "پرفروش",
        details: { nutrition_info: "500 kcal", ingredients: "مخلوط" }
    },
    // --- دسته ۱۲: فینگر فود و مزه ---
    {
        id: 12001,
        categoryId: 12,
        name: "پیراشکی گوشت و قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«پیراشکی گوشت و قارچ؛ ترکیبی خوش‌عطر و اشتها‌آور.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تازه، گوشت چرخ‌کرده، قارچ، پیاز، ادویه‌های معطر، مقدار کمی پنیر و سس مخصوص" }
    },
    {
        id: 12002,
        categoryId: 12,
        name: "پیراشکی مرغ قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«پیراشکی مرغ و قارچ با طعمی گرم و دلنشین.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ ریزشده، قارچ، خمیر تازه، ادویه‌های ملایم ، سس مخصوص" }
    },
    {
        id: 12003,
        categoryId: 12,
        name: "پیراشکی پیتزایی",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«پیراشکی پیتزایی با عطروطعمی که اشتها را باز می‌کند.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تازه ،ژامبون مخصوص ،قارچ ،سس مخصوص ،" }
    },
    {
        id: 12005,
        categoryId: 12,
        name: "مینی برگر",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«مینی‌برگر با گوشت مزه‌دار و نان سبک.»",
        image: "image1/124.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "گوشت چرخ‌کرده، نان کوچک برگر، کاهو، خیارشور، سس مخصوص و ادویه برگر" }
    },
{
        id: 12006,
        categoryId: 12,
        name: "مینی چیز برگر",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: ".",
        image: "image1/140.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "گوشت چرخ‌کرده، نان کوچک برگر، پنیر، کاهو ،خیارشور، سس مخصوص و ادویه برگر" }
    },
    {
        id: 12007,
        categoryId: 12,
        name: "مینی چیکن برگر",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: ".",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ ،نان کوچک برگر، پنیر، کاهو ،خیارشور، سس مخصوص و ادویه مخصوص." }
    },
    {
        id: 12008,
        categoryId: 12,
        name: "مینی ساندویچ ژامبون",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "ترکیبی ساده و خوش‌مزه",
        image: "image1/75.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ژامبون ،نان کوچک برگر، پنیر، کاهو ،خیارشور، سس مخصوص و ادویه مخصوص." }
    },
    {
        id: 12009,
        categoryId: 12,
        name: "مینی ساندویچ الویه",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«مینی‌ساندویچ الویه با مزه‌ی سبک و بافت نرم.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سالاد الویه تازه، نان کوچک ساندویچی، خیارشور و کمی ادویه ملایم" }
    },
    {
        id: 12010,
        categoryId: 12,
        name: "مینی ساندویچ مرغ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: ".",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ ،نان کوچک برگر، پنیر، کاهو ،خیارشور، سس مخصوص و ادویه مخصوص."}
    },
    {
        id: 12011,
        categoryId: 12,
        name: "مینی ساندویچ فلافل",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«مینی‌ساندویچ فلافل ترد و گیاهی با طعمی اصیل و تازه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "فلافل تازه، نان کوچک، خیارشور، کاهو، گوجه، سس مخصوص و ادویه‌های گیاهی" }
    },
    {
        id: 12012,
        categoryId: 12,
        name: "مینی هات داگ",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "«مینی‌هات‌داگ دودی و آبدار با نان نرم و سس تند.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "هات‌داگ دودی، نان کوچک، کاهو، خیارشور، سس خردل و کچاپ" }
    },
    {
        id: 12013,
        categoryId: 12,
        name: "رول لازنیا",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "«رول لازانیا پرشده با مواد غنی و پنیر ذوب‌شده.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ورقه لازانیا، گوشت چرخ‌کرده، سس گوجه، پنیر موزارلا، سبزیجات و ادویه ایتالیایی" }
    },
    {
        id: 12014,
        categoryId: 12,
        name: "پیراشکی سوخاری",
        price: 68000,
        priceText: "۶۸,۰۰۰ تومان",
        description: "«پیراشکی سوخاری طلایی با داخل نرم و پرمزه.»",
        image: "image1/145.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تازه، مواد پرکننده (گوشت یا سبزیجات)، ادویه‌ها و روغن برای سرخ کردن" }
    },
    {
        id: 12015,
        categoryId: 12,
        name: "فیله سوخاری",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«فیله سوخاری مرغ ترد با پوشش طلایی و آبدار.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "فیله مرغ، آرد سوخاری، ادویه‌های مرغ، تخم‌مرغ و روغن" }
    },
    {
        id: 12016,
        categoryId: 12,
        name: "رول ژامبون سوخاری",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "«رول ژامبون سوخاری با پنیر ذوب‌شده و طعم دودی.»",
        image: "image1/121.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ژامبون، پنیر، خمیر رول، آرد سوخاری و ادویه‌ها" }
    },
    {
        id: 12017,
        categoryId: 12,
        name: "توپک مرغ پنیری سوخاری",
        price: 45000,
        priceText: "۴۵,۰۰۰ تومان",
        description: "«توپک مرغ پنیری سوخاری با داخل چسبناک و خوشمزه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ چرخ‌کرده، پنیر، آرد سوخاری، ادویه‌ها و تخم‌مرغ" }
    },
    {
        id: 12018,
        categoryId: 12,
        name: "توپک سیب زمینی پنیری سوخاری",
        price: 45000,
        priceText: "۴۵,۰۰۰ تومان",
        description: "«توپک سیب‌زمینی پنیری سوخاری با بافت نرم و ترد.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سیب‌زمینی پوره، پنیر، آرد سوخاری، سبزیجات و ادویه‌ها" }
    },
    {
        id: 12019,
        categoryId: 12,
        name: "دونات مرغ سوخاری",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«دونات مرغ سوخاری نوآورانه با طعم منحصربه‌فرد.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ، خمیر دونات، آرد سوخاری، ادویه‌ها و سس" }
    },
    {
        id: 12020,
        categoryId: 12,
        name: "شات اسپرینگ رول",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«شات اسپرینگ‌رول کوچک و ترد با مواد تازه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ورقه اسپرینگ‌رول، سبزیجات، مرغ یا گوشت، ادویه آسیایی" }
    },
    {
        id: 12021,
        categoryId: 12,
        name: "شات سالاد ماکارونی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«شات سالاد ماکارونی خامه‌ای و تازه با سبزیجات.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ماکارونی، مرغ، خیارشور، ذرت، سس مایونز و ادویه" }
    },
    {
        id: 12022,
        categoryId: 12,
        name: "شات فیله سوخاری",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«شات فیله سوخاری مرغ با پوشش ترد و سس.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "فیله مرغ، آرد سوخاری، سس مخصوص و ادویه‌ها" }
    },
    {
        id: 12023,
        categoryId: 12,
        name: "شات کشک بادمجان",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "«شات کشک بادمجان سنتی با طعم دودی و غلیظ.»",
        image: "image1/66.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "بادمجان کبابی، کشک، پیاز داغ، نعنا و گردو" }
    },
    {
        id: 12024,
        categoryId: 12,
        name: "شات قفقازی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«شات قفقازی با مواد تازه و طعم اصیل.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ، سبزیجات، سس مخصوص، ادویه قفقازی و پنیر" }
    },
    {
        id: 12025,
        categoryId: 12,
        name: "شات سالادالویه",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«شات سالاد الویه خامه‌ای و تازه با تزیین.»",
        image: "image1/142.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سیب‌زمینی، مرغ، خیارشور، نخودفرنگی، سس مایونز" }
    },
    {
        id: 12026,
        categoryId: 12,
        name: "مینی پیتزا گوشت قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«مینی‌پیتزا گوشت و قارچ با پنیر ذوب‌شده و عطر سیر.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر پیتزا، گوشت چرخ‌کرده، قارچ، پنیر، سس گوجه و ادویه" }
    },
    {
        id: 12027,
        categoryId: 12,
        name: "مینی پیتزا مرغ و قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«مینی‌پیتزا مرغ و قارچ سبک و خوش‌عطر.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر پیتزا، مرغ ریز شده، قارچ، پنیر، سس و ادویه ملایم" }
    },
    {
        id: 12028,
        categoryId: 12,
        name: "مینی پیتزا پپرونی",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«مینی‌پیتزا پپرونی تند و جذاب با پنیر فراوان.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر پیتزا، پپرونی، پنیر موزارلا، سس گوجه و فلفل" }
    },
    {
        id: 12029,
        categoryId: 12,
        name: "مینی پیتزای سوسیس و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«مینی‌پیتزا سوسیس و قارچ با طعم دودی و تازه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر پیتزا، سوسیس، قارچ، پنیر، سس و ادویه" }
    },
    {
        id: 12031,
        categoryId: 12,
        name: "بورک گوشت و قارچ",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«بورک گوشت و قارچ لایه‌لایه با خمیر نازک.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر یوفکا، گوشت چرخ‌کرده، قارچ، پیاز و ادویه" }
    },
    {
        id: 12032,
        categoryId: 12,
        name: "بورک مرغ و قارچ",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«بورک مرغ و قارچ سبک با لایه‌های ترد.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر یوفکا، مرغ، قارچ، پنیر و ادویه ملایم" }
    },
    {
        id: 12033,
        categoryId: 12,
        name: "بورک سوسیس و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«بورک سوسیس و قارچ دودی و خوشمزه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر یوفکا، سوسیس، قارچ، پنیر و ادویه" }
    },
    {
        id: 12034,
        categoryId: 12,
        name: "تارت گوشت و قارچ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«تارت گوشت و قارچ با پایه ترد و مواد غنی.»",
        image: "image1/71.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تارت، گوشت، قارچ، پنیر و سبزیجات" }
    },
    {
        id: 12035,
        categoryId: 12,
        name: "تارت مرغ و قارچ",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«تارت مرغ و قارچ سبک با طعم دلنشین.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تارت، مرغ، قارچ، پنیر و ادویه" }
    },
    {
        id: 12036,
        categoryId: 12,
        name: "تارت کشک بادمجان",
        price: 50000,
        priceText: "۵۰,۰۰۰ تومان",
        description: "«تارت کشک بادمجان سنتی با عطر دودی.»",
        image: "image1/65.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر تارت، بادمجان، کشک، پیاز داغ و نعنا" }
    },
    {
        id: 12037,
        categoryId: 12,
        name: "کیک مرغ تکنفره",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«کیک مرغ تک‌نفره لایه‌لایه و خوشمزه.»",
        image: "image1/43.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "نان تست، مرغ، سس، سبزیجات و پنیر" }
    },
    {
        id: 12038,
        categoryId: 12,
        name: "کیک مرغ کیلویی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "«کیک مرغ کیلویی برای مهمانی‌های بزرگ با طعم عالی.»",
        image: "image1/25.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "نان، مرغ پخته، سس مایونز، سبزیجات تازه و ادویه" }
    },
    {
        id: 12039,
        categoryId: 12,
        name: "کوکو لوبیا",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«کوکو لوبیا گیاهی و مغذی با بافت نرم.»",
        image: "image1/122.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "لوبیا، تخم‌مرغ، سبزیجات، پیاز و ادویه ایرانی" }
    },
    {
        id: 12040,
        categoryId: 12,
        name: "کوکو سبزی",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«کوکو سبزی تازه و معطر با سبزیجات ارگانیک.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سبزی کوکو، تخم‌مرغ، آرد، گردو و ادویه" }
    },
    {
        id: 12041,
        categoryId: 12,
        name: "قیف الویه",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«قیف الویه خلاقانه با سالاد تازه و نان ترد.»",
        image: "image1/111.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سالاد الویه، نان قیفی، خیارشور و تزیین سبزی" }
    },
    {
        id: 12042,
        categoryId: 12,
        name: "سالاد الویه کیلویی",
        price: 800000,
        priceText: "۸۰۰,۰۰۰ تومان",
        description: "«سالاد الویه کیلویی تازه و خامه‌ای برای مهمانی.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سیب‌زمینی، مرغ، خیارشور، نخودفرنگی، هویج و سس" }
    },
    {
        id: 12043,
        categoryId: 12,
        name: "قفقاز کیلویی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "«قفقاز کیلویی با مواد اصیل و طعم غنی.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ، سبزیجات، پنیر، سس مخصوص و ادویه قفقازی" }
    },
    {
        id: 12044,
        categoryId: 12,
        name: "کشک بادمجان کیلویی",
        price: 800000,
        priceText: "۸۰۰,۰۰۰ تومان",
        description: "«کشک بادمجان کیلویی دودی و سنتی.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "بادمجان، کشک، پیاز داغ، نعنا داغ و گردو" }
    },
    {
        id: 12045,
        categoryId: 12,
        name: "سالاد ماکارونی کیلویی",
        price: 700000,
        priceText: "۷۰۰,۰۰۰ تومان",
        description: "«سالاد ماکارونی کیلویی خامه‌ای و رنگارنگ.»",
        image: "image1/31.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ماکارونی، مرغ، ذرت، خیارشور، سس و سبزیجات" }
    },
    {
        id: 12046,
        categoryId: 12,
        name: "ته چین مرغ زعفرانی ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«ته‌چین مرغ زعفرانی طلایی و معطر.»",
        image: "image1/44.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "برنج، مرغ، زعفران، ماست، تخم‌مرغ و ادویه" }
    },
    {
        id: 12047,
        categoryId: 12,
        name: "ته چین مرغ زعفرانی قالبی",
        price: 110000,
        priceText: "۱۱۰,۰۰۰ تومان",
        description: "«ته‌چین مرغ زعفرانی قالبی زیبا و خوش‌طعم.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "برنج زعفرانی، مرغ مزه‌دار، ماست، تخم‌مرغ و زرشک" }
    },
    {
        id: 12048,
        categoryId: 12,
        name: "سالاد سزار",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«سالاد سزار کلاسیک با مرغ گریل و سس مخصوص.»",
        image: "image1/127.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "کاهو، مرغ گریل، پنیر پارمسان، نان کروتون و سس سزار" }
    },
    {
        id: 12049,
        categoryId: 12,
        name: "سالاد کلم",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«سالاد کلم تازه و ترد با سس خامه‌ای.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "کلم سفید و قرمز، هویج، سس مایونز و ادویه" }
    },
    {
        id: 12050,
        categoryId: 12,
        name: "سالاد کلم",
        price: 59000,
        priceText: "۵۹,۰۰۰ تومان",
        description: "«سالاد کلم غنی‌شده با مواد اضافی و تازه.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "کلم، هویج، کشمش، سس مخصوص و گردو" }
    },
    {
        id: 12051,
        categoryId: 12,
        name: "سالاد مرغ",
        price: 59000,
        priceText: "۵۹,۰۰۰ تومان",
        description: "«سالاد مرغ تازه با سبزیجات رنگارنگ و سس.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "مرغ گریل، کاهو، گوجه، خیار، ذرت و سس" }
    },
    {
        id: 12052,
        categoryId: 12,
        name: "سالاد اندونزی",
        price: 58000,
        priceText: "۵۸,۰۰۰ تومان",
        description: "«سالاد اندونزی شیرین و ترش با میوه و سبزی.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "کلم، هویج، کشمش، آناناس، سس مخصوص" }
    },
    {
        id: 12053,
        categoryId: 12,
        name: "سالاد روسی",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«سالاد روسی کلاسیک با سبزیجات پخته و سس.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سیب‌زمینی، هویج، نخودفرنگی، خیارشور و سس مایونز" }
    },
    {
        id: 12054,
        categoryId: 12,
        name: "سمبوسه",
        price: 55000,
        priceText: "۵۵,۰۰۰ تومان",
        description: "«سمبوسه ترد با مواد پرشده و ادویه تند.»",
        image: "image1/fingerfood1.png",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "خمیر سمبوسه، گوشت یا سبزیجات، پیاز، ادویه هندی" }
    },
    {
        id: 12055,
        categoryId: 12,
        name: "اسپرینگ رول",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«اسپرینگ‌رول آسیایی ترد با سبزیجات تازه.»",
        image: "image1/45.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ورقه رول، سبزیجات، مرغ یا میگو، سس سویا" }
    },
    {
        id: 12056,
        categoryId: 12,
        name: "رولت الویه",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«رولت الویه نرم و تازه با تزیین زیبا.»",
        image: "image1/107.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "سالاد الویه، نان رولت، خیارشور و سبزی" }
    },
    {
        id: 12057,
        categoryId: 12,
        name: "خیار ماست",
        price: 25000,
        priceText: "۲۵,۰۰۰ تومان",
        description: "«خیار ماست تازه و خنک با نعنا و سیر.»",
        image: "image1/130.jpg",
        rating: 4.5,
        badge: "پرفروش",
        details: { nutrition_info: "پُرخوراک و مناسب برای سرو به‌عنوان میان‌وعده یا پیش‌غذا", ingredients: "ماست، خیار، نعنا خشک، سیر و نمک" }
    },
    // --- دسته ۱۳: دسر و نوشیدنی ---
    {
        id: 13001,
        categoryId: 13,
        name: "لوتوس",
        price: 65000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«لوتوس کرمی با طعم کارامل و بیسکویت ترد.»",
        image: "image1/19.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "خامه، بیسکویت لوتوس، کارامل، وانیل و شکر" }
    },
    {
        id: 13002,
        categoryId: 13,
        name: "تیرامیسو",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "«تیرامیسو ایتالیایی با قهوه و ماسکارپونه نرم.»",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "کیک لیدی‌فینگر، قهوه، ماسکارپونه، کاکائو و تخم‌مرغ" }
    },
    {
        id: 13003,
        categoryId: 13,
        name: "روکر موز",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«روکر موز تازه با لایه‌های خامه و بیسکویت.»",
        image: "image1/2.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "موز، خامه، بیسکویت، وانیل و شکر قهوه‌ای" }
    },
    {
        id: 13004,
        categoryId: 13,
        name: "چیز کیک لوتوس",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "«چیزکیک لوتوس کرمی با پایه بیسکویتی ترد.»",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "پنیر خامه‌ای، بیسکویت لوتوس، خامه، شکر و وانیل" }
    },
    {
        id: 13005,
        categoryId: 13,
        name: "ژله بستنی",
        price: 40000,
        priceText: "۴۰,۰۰۰ تومان",
        description: "«ژله بستنی رنگارنگ و خنک با طعم میوه.»",
        image: "image1/5.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "ژله میوه‌ای، بستنی وانیلی، میوه تازه و شکر" }
    },
    {
        id: 13006,
        categoryId: 13,
        name: "کرم توت فرنگی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«کرم توت‌فرنگی تازه و سبک با عطر طبیعی.»",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "خامه، توت‌فرنگی تازه، شکر، وانیل و ژلاتین" }
    },
    {
        id: 13007,
        categoryId: 13,
        name: "دسر شکلاتی ",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«دسر شکلاتی غلیظ و خوشمزه با لایه‌های متنوع.»",
        image: "image1/4.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "شکلات تلخ، خامه، شکر، وانیل و بیسکویت" }
    },
    {
        id: 13008,
        categoryId: 13,
        name: "کرم زعفرانی",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«کرم زعفرانی معطر و طلایی با طعم ایرانی.»",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "خامه، زعفران، شکر، وانیل و پسته" }
    },
    {
        id: 13009,
        categoryId: 13,
        name: "کرم وانیلی",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«کرم وانیلی نرم و کلاسیک با عطر دلنشین.»",
        image: "image1/144.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "خامه، وانیل طبیعی، شکر، شیر و ژلاتین" }
    },
    {
        id: 13010,
        categoryId: 13,
        name: "چیز کیک رافائل",
        price: 70000,
        priceText: "۷۰,۰۰۰ تومان",
        description: "«چیزکیک رافائل با نارگیل و شکلات سفید.»",
        image: "image1/68.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "پنیر خامه‌ای، نارگیل، شکلات سفید، بادام و شکر" }
    },
    {
        id: 13011,
        categoryId: 13,
        name: "خاگینه مغز دار",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«خاگینه مغزی سنتی با مغز گردو و دارچین.»",
        image: "image1/fingerfood3.png",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "تخم‌مرغ، شکر، گردو، دارچین و روغن" }
    },
    {
        id: 13012,
        categoryId: 13,
        name: "حلوا فیروزه",
        price: 65000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«حلوا فیروزه نرم و معطر با زعفران و پسته.»",
        image: "image1/113.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "آرد، شکر، زعفران، روغن، پسته و گلاب" }
    },
    {
        id: 13013,
        categoryId: 13,
        name: "شربت زعفران",
        price: 60000,
        priceText: "۶۰,۰۰۰ تومان",
        description: "«شربت زعفران خنک و معطر برای روزهای گرم.»",
        image: "image1/125.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "زعفران، شکر، آب، گلاب و لیمو" }
    },
    {
        id: 13014,
        categoryId: 13,
        name: "کاپ کیک ساده",
        price: 41000,
        priceText: "۴۱,۰۰۰ تومان",
        description: "«کاپ‌کیک ساده وانیلی با بافت نرم و سبک.»",
        image: "image1/119.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "آرد، شکر، تخم‌مرغ، وانیل و بکینگ‌پودر" }
    },
    {
        id: 13015,
        categoryId: 13,
        name: "کاپ کیک ساده فیلنگ دار",
        price: 46000,
        priceText: "۴۶,۰۰۰ تومان",
        description: "«کاپ‌کیک فیلینگ‌دار با پرکننده میوه‌ای یا شکلاتی.»",
        image: "image1/118.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "آرد، شکر، فیلینگ میوه یا شکلات، وانیل و خامه" }
    },
    {
        id: 13016,
        categoryId: 13,
        name: "پاناکوتا",
        price: 60000,
        priceText: "۶۵,۰۰۰ تومان",
        description: "«پاناکوتا ایتالیایی نرم با سس میوه.»",
        image: "image1/117.jpg",
        rating: 4.8,
        badge: "تخفیف",
        details: { nutrition_info: "200 kcal", ingredients: "خامه، شیر، شکر، ژلاتین و سس میوه" }
    },
    // --- دسته ۱۴: وی‌آی‌پی (VIP) ---
    {
        id: 14001,
        categoryId: 14,
        name: "سینی رویال وی‌آی‌پی",
        price: 900000,
        priceText: "۹۰۰,۰۰۰ تومان",
        description: "«سینی رویال وی‌آی‌پی لوکس با مواد premium و تزیین حرفه‌ای.»",
        image: "image1/vip1.png",
        rating: 5.0,
        badge: "ویژه",
        details: { nutrition_info: "800 kcal", ingredients: "خاویار، سالمون دودی، پنیرهای خاص، میوه‌های استوایی و نان‌های artisanal" }
    },

    // --- دسته ۱۵: نیمه آماده ---
    {
        id: 15001,
        categoryId: 15,
        name: "الویه نیمه آماده",
        price: 120000,
        priceText: "۱۲۰,۰۰۰ تومان",
        description: "«الویه نیمه‌آماده تازه برای ترکیب سریع و آسان.»",
        image: "image1/semi1.png",
        rating: 4.2,
        badge: "",
        details: { nutrition_info: "300 kcal", ingredients: "سیب‌زمینی پخته، مرغ آماده، خیارشور خردشده، نخودفرنگی و هویج" }
    },
    {
        id: 15002,
        categoryId: 15,
        name: "رول سوخاری نیمه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "«رول سوخاری نیمه‌آماده برای سرخ کردن سریع.»",
        image: "image1/87.jpg",
        rating: 4.2,
        badge: "",
        details: { nutrition_info: "300 kcal", ingredients: "خمیر رول، مواد پرکننده (ژامبون یا مرغ)، پنیر و ادویه آماده" }
    },
    {
        id: 15003,
        categoryId: 15,
        name: "سمبوسه نیه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "«سمبوسه نیمه‌آماده با مواد تازه برای پخت آسان.»",
        image: "image1/86.jpg",
        rating: 4.2,
        badge: "",
        details: { nutrition_info: "300 kcal", ingredients: "خمیر سمبوسه، گوشت یا سبزیجات آماده، پیاز و ادویه" }
    },
    {
        id: 15003,
        categoryId: 15,
        name: "بورک مرغ و قارچ نیمه اماده",
        price: 50000,
        priceText: ",۵۰۰۰۰ تومان",
        description: "«بورک مرغ و قارچ نیمه‌آماده برای پخت سریع.»",
        image: "image1/83.jpg",
        rating: 4.2,
        badge: "",
        details: { nutrition_info: "300 kcal", ingredients: "خمیر یوفکا، مرغ و قارچ آماده، پنیر و ادویه" }
    },

    // --- دسته ۱۶: خدمات سازمانی ---
    {
        id: 16001,
        categoryId: 16,
        name: "پک صبحانه سازمانی",
        price: 85000,
        priceText: "۸۵,۰۰۰ تومان",
        description: "«پک صبحانه سازمانی کامل و مغذی برای جلسات اداری.»",
        image: "image1/org1.png",
        rating: 4.6,
        badge: "اقتصادی",
        details: { nutrition_info: "450 kcal", ingredients: "نان تازه، پنیر، گردو، مربا، چای یا قهوه و میوه" }
    }
];