# Generated by Django 5.2.15 on 2026-07-19 08:01

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[apps.authentication.validators.validate_iranian_phone]),
        ),
    ]
