# Generated by Django 5.2.15 on 2026-07-10 07:24

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.category_image_upload_path),
        ),
    ]
