# Generated by Django 5.2.15 on 2026-07-19 08:01

import apps.products.models
import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload_path, validators=[apps.products.validators.validate_image_size]),
        ),
    ]
